name: smart_car_ai_alert
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General Flutter dependencies
  cupertino_icons: ^1.0.8

 
  intl: ^0.18.1
  video_player: ^2.7.0
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1

  # Firebase dependencies
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.4
  cloud_firestore: ^4.15.4
    
  firebase_auth: ^4.2.5 
  
  firebase_storage_web: ^3.7.4  # Ensure you're using a web-compatible version
  cloud_firestore_web: ^3.10.8  # Ensure you're using a web-compatible version 

  http_parser: ^4.0.2


  # Permission handling
 

  # Audio recording
 

  record_mp3_plus: ^1.0.0  # Updated to the latest working version for MP3 recording
  record: ^3.0.0
  audioplayers: ^6.4.0           # ✅ Latest stable
  http: ^1.4.0                   # ✅ Latest stable
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets section (Ensure your assets are correctly added)
  assets:
    - images/background.jpg
    - images/background2.jpg
    - images/video_thumbnail_placeholder.jpg
    - images/image_placeholder.png
